FROM mcr.microsoft.com/devcontainers/go:1-1.22-bookworm

COPY ./.devcontainer/scripts/install-opentelemertry-generator.sh /tmp/install-opentelemertry-generator.sh

RUN bash /tmp/install-opentelemertry-generator.sh