services:
  observability-telemetry-generator:
    build:
      context: ../
      dockerfile: .devcontainer/dockerfile.dev
    volumes:
      - ./.zshrc:/home/neil/.zshrc
      - ../:/workspaces      
    command: sleep infinity
    networks:
      - local-dev

networks:
  local-dev:
    driver: bridge
    external: true