services:
  observability-telemetry-generator:
    build:
      context: ../
      dockerfile: .devcontainer/dockerfile.dev
    volumes:
      - ./.zshrc:/home/vscode/.zshrc
      - ../:/workspaces      
      - /var/run/docker.sock:/var/run/docker.sock
    command: sleep infinity
    networks:
      - local-dev

networks:
  local-dev:
    driver: bridge
    external: true